name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Add additional build steps for Python stack here

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add test steps for Python stack here

  deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

      - name: Deploy to EC2/VM
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }} ec2-user@18.206.247.56 "rsync -r --delete-after $GITHUB_WORKSPACE/ user@ec2-18-206-247-56.compute-1.amazonaws.com:/path/to/app"
          # Add additional deployment steps as needed

secrets:
  DEPLOY_SSH_PRIVATE_KEY:
    # Add your SSH private key here

# Don't forget to configure the DEPLOY_SSH_PRIVATE_KEY secret with the correct SSH private key if deploying to an EXISTING VM